create_table_stmt ::=   CREATE
                        [ TEMP | TEMPORARY ]
                        TABLE [ IF NOT EXISTS ] [ database_name '.' ]
                        table_name ( '(' column_def ( ',' column_def ) *
                        ( ',' table_constraint ) * ')'
                        [ WITHOUT ROWID ] | AS select_stmt )



column_def ::= column_name [ type_name ] ( column_constraint ) *



column_constraint ::= [ CONSTRAINT name ]
                        ( PRIMARY KEY [ ASC | DESC ]
                        conflict_clause [ AUTOINCREMENT ] |
                        NOT NULL conflict_clause |
                        UNIQUE conflict_clause |
                        CHECK '(' expr ')' |
                        DEFAULT ( signed_number |
                        literal_value | '(' expr ')' ) |
                        COLLATE collation_name |
                        foreign_key_clause )

conflict_clause ::= [ ON CONFLICT ( ROLLBACK | ABORT | FAIL | IGNORE | REPLACE ) ]

table_constraint ::=    [ CONSTRAINT name ]
                        (
                        ( PRIMARY KEY | UNIQUE )
                        '(' indexed_column
                        ( ',' indexed_column ) * ')'
                        conflict_clause |
                        CHECK '(' expr ')' |
                        FOREIGN KEY '(' column_name ( ',' column_name ) * ')' foreign_key_clause )

foreign_key_clause ::=  REFERENCES foreign_table
                        [ '(' column_name ( ',' column_name ) * ')' ]
                        [ ( ON ( DELETE | UPDATE ) ( SET NULL | SET DEFAULT | CASCADE | RESTRICT | NO ACTION ) | MATCH name ) ]
                        [ [ NOT ] DEFERRABLE [ INITIALLY DEFERRED | INITIALLY IMMEDIATE ] ]
